map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: ""

amcl:
  ros__parameters:
    use_sim_time: false
    alpha1: 0.20
    alpha2: 0.20
    alpha3: 0.20
    alpha4: 0.20
    alpha5: 0.20
    base_frame_id: base_link
    global_frame_id: map
    odom_frame_id: odom
    scan_topic: scan
    robot_model_type: nav2_amcl::DifferentialMotionModel
    min_particles: 500
    max_particles: 2000
    update_min_d: 0.10
    update_min_a: 0.10
    transform_tolerance: 0.50
    laser_min_range: 0.35
    laser_max_range: 25.0
    max_beams: 120
    tf_broadcast: true
    set_initial_pose: false

planner_server:
  ros__parameters:
    use_sim_time: false
    expected_planner_frequency: 2.0
    planner_plugins: [GridBased]
    GridBased:
      plugin: nav2_navfn_planner/NavfnPlanner
      tolerance: 0.50
      use_astar: true
      allow_unknown: false

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: false
      update_frequency: 2.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      robot_radius: 0.34
      resolution: 0.05
      track_unknown_space: true
      transform_tolerance: 0.50
      plugins: [static_layer, obstacle_layer, inflation_layer]
      static_layer:
        plugin: nav2_costmap_2d/StaticLayer
        map_subscribe_transient_local: true
      obstacle_layer:
        plugin: nav2_costmap_2d/ObstacleLayer
        enabled: true
        observation_sources: scan
        scan:
          topic: /scan
          data_type: LaserScan
          clearing: true
          marking: true
          obstacle_max_range: 8.0
          raytrace_max_range: 10.0
          obstacle_min_range: 0.35
          raytrace_min_range: 0.35
      inflation_layer:
        plugin: nav2_costmap_2d/InflationLayer
        inflation_radius: 0.55
        cost_scaling_factor: 3.0
      always_send_full_costmap: true

lifecycle_manager_route:
  ros__parameters:
    use_sim_time: false
    autostart: true
    node_names: [map_server, amcl, planner_server]
