hunav_loader:
  ros__parameters:
    yaml_base_name: agents_training_detour_oncoming_joint_recovery
    simulator: Gazebo Classic
    map: training_detour_oncoming
    publish_people: true
    global_goals:
      1:
        x: 9.000
        y: 2.000
      2:
        x: -2.500
        y: 2.000
    agents:
      - agent1
    agent1:
      id: 1
      group_id: -1
      skin: 2
      max_vel: 0.75
      radius: 0.33
      goal_radius: 0.45
      cyclic_goals: false
      init_pose:
        x: 9.000
        y: 2.000
        z: 1.250
        h: 3.14159
      behavior:
        type: Regular
        configuration: 1
        goal_force_factor: 2.0
        obstacle_force_factor: 5.0
        social_force_factor: 2.2
        other_force_factor: 6.0
      goals:
        - 2
